version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Preparing the build environment...
  build:
    commands:
      - echo "Hello World"
  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - "**/*"
